version: '3'
services:
    user-api:
        build: ./user-api
        ports: 
            - "4001:4001"
        restart: always

    mimo-api:
        build: ./mimo-api
        ports: 
            - "4000:4000"
        restart: always

    gateway:
        depends_on: 
            - user-api
            - mimo-api
        build: ./editor-gateway
        ports: 
            - "4002:4002"
        restart: always

    client:
        depends_on:
            - user-api
            - mimo-api
            - gateway
        build: ./client
        ports: 
            - "3000:3000"
        restart: always